### ISSUE TITLE
Import Problem

### ISSUE THREAD

**Issue by msarvestani** [alimuldal/PyFNND#2]
When running setup.py from root, or using easy_install, to load the package, I get the following error. Any suggestions (windows 8 machine, python 2.7)? 

import pyfnnd

Traceback (most recent call last):

  File "<ipython-input-1-e38a50e30ffc>", line 1, in <module>
    import pyfnnd

  File "build\bdist.win-amd64\egg\pyfnnd\__init__.py", line 1, in <module>

  File "build\bdist.win-amd64\egg\pyfnnd\_fnndeconv.py", line 6, in <module>

  File "build\bdist.win-amd64\egg\pyfnnd\_tridiag_solvers.py", line 12, in <module>

  File "C:\Users\msarvestani\Anaconda\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)

  File "C:\Users\msarvestani\Anaconda\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)

WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by msarvestani** [comment]
It was an architecture issue. Everything works with 32-bit python.

**Comment by alimuldal** [comment]
Was the issue that you were trying to link against a 32 bit LAPACK from 64 bit Python?

**Comment by alimuldal** [comment]
I'm closing this for the time being, since it seems most likely to be an issue with your environment

**Comment by msarvestani** [comment]
It was (trying to linka against a 32 bit LAPACK from 64 bit python). Thanks.
